before:
  hooks:
    - go mod download
    - go generate ./...

builds:
  - id: v-agent
    main: ./cmd/v-agent/main.go
    binary: v-agent
    env:
      - CGO_ENABLED=0
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath #removes all file system paths from the compiled executable
    goos:
      - linux
    goarch:
      - amd64
      - arm64

dockers:
  - dockerfile: cmd/v-agent/Dockerfile.goreleaser
    use: buildx
    build_flag_templates:
    - "--pull"
    - "--platform=linux/amd64"
    image_templates:
      - "ewr.vultrcr.com/vagent/v-agent:latest-amd64"
      - "ewr.vultrcr.com/vagent/v-agent:{{ .Tag }}-amd64"
    extra_files:
      - "cmd/v-agent/config.yaml"
  - dockerfile: cmd/v-agent/Dockerfile.goreleaser
    use: buildx
    goarch: arm64
    build_flag_templates:
    - "--pull"
    - "--platform=linux/arm64/v8"
    image_templates:
      - "ewr.vultrcr.com/vagent/v-agent:latest-arm64"
      - "ewr.vultrcr.com/vagent/v-agent:{{ .Tag }}-arm64"
    extra_files:
      - "cmd/v-agent/config.yaml"

docker_manifests:
- name_template: 'ewr.vultrcr.com/vagent/v-agent:latest'
  image_templates:
  - 'ewr.vultrcr.com/vagent/v-agent:latest-amd64'
  - 'ewr.vultrcr.com/vagent/v-agent:latest-arm64'
- name_template: 'ewr.vultrcr.com/vagent/v-agent:{{ .Tag }}'
  image_templates:
  - 'ewr.vultrcr.com/vagent/v-agent:{{ .Tag }}-amd64'
  - 'ewr.vultrcr.com/vagent/v-agent:{{ .Tag }}-arm64'

archives:
  - id: v-agent
    builds:
      - v-agent
    format: zip
    files:
      - README.md
      - src: cmd/v-agent/config.yaml
        strip_parent: true
    name_template: "v-agent_v{{ .Version }}_{{ .Os }}_{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256
  ids:
    - v-agent

blobs:
  - provider: s3
    endpoint: https://tartarus.vultr.dev
    region: us-midwest-1
    bucket: vke-bins
    ids:
      - v-agent
    folder: "v-agent/v{{.Version}}/"

release:
  draft: false

changelog:
  skip: false
