apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app: v-agent
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  name: v-agent
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |-
    ---
    debug: true
    interval: {{ .Values.config.interval }}
    endpoint: {{ .Values.config.endpoint }}
    basic_auth_user: "{{ .Values.config.basic_auth_user }}"
    basic_auth_pass: "{{ .Values.config.basic_auth_pass }}"
    check_vendor: false
    probes_api:
      listen: {{ .Values.config.probes_api.listen }}
      port: {{ .Values.config.probes_api.port }}
    labels_config:
{{ toYaml .Values.config.labels_config | indent 6 }}
    metrics_config:
      agent:
        load_avg:
          enabled: {{ .Values.config.metrics_config.agent.load_avg.enabled }}
        cpu:
          enabled: {{ .Values.config.metrics_config.agent.cpu.enabled }}
        memory:
          enabled: {{ .Values.config.metrics_config.agent.memory.enabled }}
        nic:
          enabled: {{ .Values.config.metrics_config.agent.nic.enabled }}
        disk_stats:
          enabled: {{ .Values.config.metrics_config.agent.disk_stats.enabled }}
          filter: "sr0" # regex
        file_system:
          enabled: {{ .Values.config.metrics_config.agent.file_system.enabled }}
        kubernetes:
          enabled: {{ .Values.config.metrics_config.agent.kubernetes.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.kubernetes.endpoint }}
          kubeconfig: /var/lib/kubernetes/admin.kubeconfig
        konnectivity:
          enabled: {{ .Values.config.metrics_config.agent.konnectivity.enabled }}
          metrics_endpoint: {{ .Values.config.metrics_config.agent.konnectivity.metrics_endpoint }}
          health_endpoint: {{ .Values.config.metrics_config.agent.konnectivity.health_endpoint }}
        etcd:
          enabled: {{ .Values.config.metrics_config.agent.etcd.enabled }}
          cacert: /var/lib/kubernetes/ca.pem
          cert: /var/lib/kubernetes/kubernetes.pem
          key: /var/lib/kubernetes/kubernetes-key.pem
          endpoint: {{ .Values.config.metrics_config.agent.etcd.endpoint }}
        nginx_vts:
          enabled: {{ .Values.config.metrics_config.agent.nginx_vts.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.nginx_vts.endpoint }}
        v_cdn_agent:
          enabled: {{ .Values.config.metrics_config.agent.v_cdn_agent.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.v_cdn_agent.endpoint }}
        haproxy:
          enabled: {{ .Values.config.metrics_config.agent.haproxy.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.haproxy.endpoint }}
        ceph:
          enabled: {{ .Values.config.metrics_config.agent.ceph.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.ceph.endpoint }}
        v_dns:
          enabled: {{ .Values.config.metrics_config.agent.v_dns.enabled }}
          endpoint: {{ .Values.config.metrics_config.agent.v_dns.endpoint }}
        smart:
          enabled: {{ .Values.config.metrics_config.agent.smart.enabled }}
      kubernetes:
        pods:
          enabled: {{ .Values.config.metrics_config.kubernetes.pods.enabled }}
          namespaces:
{{ toYaml .Values.config.metrics_config.kubernetes.pods.namespaces | indent 10 }}
        dcgm:
          enabled: {{ .Values.config.metrics_config.kubernetes.dcgm.enabled }}
          namespace: {{ .Values.config.metrics_config.kubernetes.dcgm.namespace }}
          endpoint: {{ .Values.config.metrics_config.kubernetes.dcgm.endpoint }}