---
apiVersion: v1
kind: Secret
metadata:
  name: vcr
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
data:
  .dockerconfigjson: {{ .Values.registryCreds }}
type: kubernetes.io/dockerconfigjson
