apiVersion: v1
kind: Service
metadata:
  name: v-agent-cip
  namespace: {{ .Release.Namespace }}
  labels:
    app: v-agent
    app.kubernetes.io/managed-by: {{ .Release.Service }}
  annotations:
    meta.helm.sh/release-namespace: {{ .Release.Namespace }}
spec:
  type: ClusterIP
  ports:
    - name: http
      port: {{ .Values.config.port }}
      protocol: TCP
      targetPort: "http"
  selector:
    app: v-agent
