debug: true
listen: 0.0.0.0
port: 7091
interval: 5
#endpoint: http://localhost:8080/api/v1/rw
endpoint: https://metrics.vultrlabs.com/api/v1/push
basic_auth_user: ""
basic_auth_pass: ""
check_vendor: false # when true, vendor must be "Vultr"; set to false on bare metal
labels_config: # any labels below will be added to all metrics
  hostname: "" # empty string uses local hostname, unset (nil) doesnt use, non-empty string uses specified label
  subid: "" # empty string pulls from userdata, unset (nil) doesnt use, non-empty string uses specified label
  vpsid: "" # empty string pulls from userdata, unset (nil) doesnt use, non-empty string uses specified label
  product: vke # unset (nil) doesnt use, non-empty string uses specified label. Note: This label is used to determine subid for vke/vlb/vfs
  any: any # any key/value label
metrics_config:
  load_avg:
    enabled: true
  cpu:
    enabled: true
  memory:
    enabled: true
  nic:
    enabled: true
  disk_stats:
    enabled: true
    filter: "sr0" # regex
  file_system:
    enabled: true
  kubernetes:
    enabled: true
    endpoint: https://localhost:6443
    kubeconfig: /var/lib/kubernetes/admin.kubeconfig
  konnectivity:
    enabled: true
    metrics_endpoint: http://localhost:8133 # /metrics
    health_endpoint: http://localhost:8092 # /healthz
  etcd:
    enabled: true
    cacert: /var/lib/kubernetes/ca.pem
    cert: /var/lib/kubernetes/kubernetes.pem
    key: /var/lib/kubernetes/kubernetes-key.pem
    endpoint: https://10.1.96.3:2379 # /metrics
  nginx_vts:
    enabled: false
    endpoint: http://localhost:9001 # /metrics
  v_cdn_agent:
    enabled: false
    endpoint: http://localhost:9093 # /metrics
  haproxy:
    enabled: false
    endpoint: http://localhost:8404 # /metrics
  ganesha:
    enabled: false
    endpoint: http://localhost:9587 # /metrics
  ceph:
    enabled: false
    endpoint: http://localhost:9283 # /metrics
  v_dns:
    enabled: false
    endpoint: http://localhost:9053 # /metrics