debug: true
listen: 0.0.0.0
port: 7091
interval: 5
#endpoint: http://localhost:8080/api/v1/rw
subid: ""
product: vke # directly attached to metrics
endpoint: https://metrics.vultrlabs.com/api/v1/push
basic_auth_user: ""
basic_auth_pass: ""
metrics_config:
  load_avg:
    enabled: true
  cpu:
    enabled: true
  memory:
    enabled: true
  nic:
    enabled: true
  disk_stats:
    enabled: true
    filter: "sr0" # regex
  file_system:
    enabled: true
  kubernetes:
    enabled: true
    endpoint: https://localhost:6443
    kubeconfig: /var/lib/kubernetes/admin.kubeconfig
  etcd:
    enabled: true
    cacert: /var/lib/kubernetes/ca.pem
    cert: /var/lib/kubernetes/kubernetes.pem
    key: /var/lib/kubernetes/kubernetes-key.pem
    endpoint: https://10.1.96.3:2379 # /metrics
