image:
  repository: ewr.vultrcr.com/vagent/v-agent
  tag: v1.0.9

replicas: 1

resources:
  requests:
    memory: "256Mi"
  limits:
    memory: "512Mi"

registryCreds: ewoJImF1dGhzIjogewoJCSJld3IudnVsdHJjci5jb20iOiB7CgkJCSJhdXRoIjogIll6QTBaVGhsTnpZdE0yRmtaaTAwTXpNMExUaGtaVFV0TVdSak16aGhOakl5WlRGbU9tZExPVTFXVTNSaFZGTkdSRmRGVVV0eE9WUm1aRnAxYldGV1RHNXZZVUptVEVOT05nPT0iCgkJfQoJfQp9

daemonset_config:
  enabled: false
  debug: true
  listen: 0.0.0.0
  port: 7091
  interval: 5
  endpoint: https://metrics.vultrlabs.com/api/v1/push
  basic_auth_user: ""
  basic_auth_pass: ""
  check_vendor: false # when true, vendor must be "Vultr"; set to false on bare metal
  labels_config: # any labels below will be added to all metrics
    hostname: ""
    product: "v-inf"
  metrics_config:
    load_avg:
      enabled: true
    cpu:
      enabled: true
    memory:
      enabled: true
    nic:
      enabled: true
    disk_stats:
      enabled: true
      filter: "sr0" # regex
    file_system:
      enabled: true
    kubernetes:
      enabled: true
      endpoint: https://localhost:6443
      kubeconfig: /var/lib/kubernetes/admin.kubeconfig
    konnectivity:
      enabled: true
      metrics_endpoint: http://localhost:8133 # /metrics
      health_endpoint: http://localhost:8092 # /healthz
    etcd:
      enabled: true
      cacert: /var/lib/kubernetes/ca.pem
      cert: /var/lib/kubernetes/kubernetes.pem
      key: /var/lib/kubernetes/kubernetes-key.pem
      endpoint: https://10.1.96.3:2379 # /metrics
    nginx_vts:
      enabled: false
      endpoint: http://localhost:9001 # /metrics
    v_cdn_agent:
      enabled: false
      endpoint: http://localhost:9093 # /metrics
    haproxy:
      enabled: false
      endpoint: http://localhost:8404 # /metrics
    ganesha:
      enabled: false
      endpoint: http://localhost:9587 # /metrics
    ceph:
      enabled: false
      endpoint: http://localhost:9283 # /metrics
    v_dns:
      enabled: false
      endpoint: http://localhost:9053 # /metrics
    smart:
      enabled: true
    kubernetes_pods:
      enabled: false
      namespaces:
      - default
    dcgm:
      enabled: false
      namespace: gpu-operator
      endpoint: nvidia-dcgm-exporter

config:
  debug: true
  listen: 0.0.0.0
  port: 7091
  interval: 5
  endpoint: https://metrics.vultrlabs.com/api/v1/push
  basic_auth_user: ""
  basic_auth_pass: ""
  check_vendor: false # when true, vendor must be "Vultr"; set to false on bare metal
  labels_config: # any labels below will be added to all metrics
    hostname: ""
    product: "v-inf"
  metrics_config:
    load_avg:
      enabled: true
    cpu:
      enabled: true
    memory:
      enabled: true
    nic:
      enabled: true
    disk_stats:
      enabled: true
      filter: "sr0" # regex
    file_system:
      enabled: true
    kubernetes:
      enabled: true
      endpoint: https://localhost:6443
      kubeconfig: /var/lib/kubernetes/admin.kubeconfig
    konnectivity:
      enabled: true
      metrics_endpoint: http://localhost:8133 # /metrics
      health_endpoint: http://localhost:8092 # /healthz
    etcd:
      enabled: true
      cacert: /var/lib/kubernetes/ca.pem
      cert: /var/lib/kubernetes/kubernetes.pem
      key: /var/lib/kubernetes/kubernetes-key.pem
      endpoint: https://10.1.96.3:2379 # /metrics
    nginx_vts:
      enabled: false
      endpoint: http://localhost:9001 # /metrics
    v_cdn_agent:
      enabled: false
      endpoint: http://localhost:9093 # /metrics
    haproxy:
      enabled: false
      endpoint: http://localhost:8404 # /metrics
    ganesha:
      enabled: false
      endpoint: http://localhost:9587 # /metrics
    ceph:
      enabled: false
      endpoint: http://localhost:9283 # /metrics
    v_dns:
      enabled: false
      endpoint: http://localhost:9053 # /metrics
    smart:
      enabled: true
    kubernetes_pods:
      enabled: false
      namespaces:
      - default
    dcgm:
      enabled: false
      namespace: gpu-operator
      endpoint: nvidia-dcgm-exporter