name: Checks

on:
  push:
  pull_request:

jobs:
  Golangci-Lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: "^1.21"
      - run: go version

      - name: Install dependencies
        run: |
          go version
          go install github.com/golangci/golangci-lint/cmd/golangci-lint@v1.54.2

      - name: Run golangci-lint
        run: |
          golangci-lint run cmd/...
          golangci-lint run metrics/...
